site_name: Weather App Documentation
# site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/
# site_url: https://example.com/
site_url: https://github.com/NitkarshChourasia

nav:
  - Home: README.md
  - Objective: 'Objective-Weather Data Management Web Application with User Authentication.md'
  - Project Overview: 'Overview of Project Structure for Weather Application.md'
  - Security Features:
      - 'Overall_security_featues.md'
      - 'How_CSRF_Protection_Enhances_Security_in_Flask_WeatherApp.md'
      - 'Password_Hashing_in_Flask_Application.md'
      - 'Implementing_Secure_Cookies_for_Enhanced_Security_in_Flask.md'
  - API & Dynamic Data:
      - 'Dynamic API Key Selection and Secure Secret Key Generation in Flask.md'
      - 'Implementing Auto-Refresh for Real-Time Weather Data in a Flask Application.md'
  - Input Validation: 'Input_Validation_Flask_Application.md'
  - Session Management: 'flask_session_timeout.md'
  - User Experience:
      - 'Seamless Night Mode Integration for Enhanced User Experience.md'
  - Logging: 'Effective Logging Practices in Flask Applications.md'
  - Challenges and Resolution: 'Challenges in Deploying a Full-Stack Weather App-Platform Limitations and Final Resolution.md'

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - dark_mode: true
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
# This switch is not appearing, make it good.

# plugins:
# - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/NitkarshChourasia
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/NitkarshC
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/ # Put mine. Here.
      link: https://www.linkedin.com/in/nitkarshchourasia



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink

copyright: |
  <!-- &copy; 2024 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">James Willett</a> -->
  &copy; 2024 <a href="https://github.com/NitkarshChourasia"  target="_blank" rel="noopener">Nitkarsh Chourasia</a>

# At the last ask bing how to improve it further.

# Make it fully, and extra loaded.
